locale                   : "en-US"
remote_theme: pages-themes/architect
title                    : "Bill Hasling / Research Software Engineer"
title_separator          : "-"
name                     : &name "Bill Hasling"
description              : &description "personal description"
url                      : https://bhasling.github.io/demo/
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "bhasling/demo"
